/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exemplo8;

/**
 *
 * @author clebe
 */
public class Exemplo8_2 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo8_2
     */
    public Exemplo8_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnExemplos = new javax.swing.JMenu();
        jItmMnExemplo3 = new javax.swing.JMenuItem();
        jItmMnExemplo4 = new javax.swing.JMenuItem();
        jItmMn5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setMnemonic('a');
        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMnExemplos.setMnemonic('e');
        jMnExemplos.setText("Exemplos");

        jItmMnExemplo3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jItmMnExemplo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/java.png"))); // NOI18N
        jItmMnExemplo3.setText("Exemplo 8.3");
        jItmMnExemplo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItmMnExemplo3ActionPerformed(evt);
            }
        });
        jMnExemplos.add(jItmMnExemplo3);

        jItmMnExemplo4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jItmMnExemplo4.setText("Exemplo 8.4");
        jItmMnExemplo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItmMnExemplo4ActionPerformed(evt);
            }
        });
        jMnExemplos.add(jItmMnExemplo4);

        jItmMn5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jItmMn5.setText("Exemplo 8.5");
        jItmMn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItmMn5ActionPerformed(evt);
            }
        });
        jMnExemplos.add(jItmMn5);

        jMenuBar1.add(jMnExemplos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jItmMnExemplo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItmMnExemplo3ActionPerformed
        Exemplo8_3 exemplo3 = new Exemplo8_3();
        exemplo3.setVisible(true);
    }//GEN-LAST:event_jItmMnExemplo3ActionPerformed

    private void jItmMnExemplo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItmMnExemplo4ActionPerformed
        Exemplo8_4 exemplo4 = new Exemplo8_4();
        exemplo4.setVisible(true);
    }//GEN-LAST:event_jItmMnExemplo4ActionPerformed

    private void jItmMn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItmMn5ActionPerformed
        Exemplo8_5 exemplo5 = new Exemplo8_5();
        exemplo5.setVisible(true);
    }//GEN-LAST:event_jItmMn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo8_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItmMn5;
    private javax.swing.JMenuItem jItmMnExemplo3;
    private javax.swing.JMenuItem jItmMnExemplo4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnExemplos;
    // End of variables declaration//GEN-END:variables
}
